./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_21.scala > ./tpch/tpch_output/tpch_output_5/output_21.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_20.scala > ./tpch/tpch_output/tpch_output_5/output_20.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_22.scala > ./tpch/tpch_output/tpch_output_5/output_22.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_18.scala > ./tpch/tpch_output/tpch_output_5/output_18.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_19.scala > ./tpch/tpch_output/tpch_output_5/output_19.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_4.scala > ./tpch/tpch_output/tpch_output_5/output_4.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_5.scala > ./tpch/tpch_output/tpch_output_5/output_5.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_7.scala > ./tpch/tpch_output/tpch_output_5/output_7.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_6.scala > ./tpch/tpch_output/tpch_output_5/output_6.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_2.scala > ./tpch/tpch_output/tpch_output_5/output_2.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_3.scala > ./tpch/tpch_output/tpch_output_5/output_3.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_1.scala > ./tpch/tpch_output/tpch_output_5/output_1.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_8.scala > ./tpch/tpch_output/tpch_output_5/output_8.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_9.scala > ./tpch/tpch_output/tpch_output_5/output_9.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_14.scala > ./tpch/tpch_output/tpch_output_5/output_14.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_15.scala > ./tpch/tpch_output/tpch_output_5/output_15.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_17.scala > ./tpch/tpch_output/tpch_output_5/output_17.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_16.scala > ./tpch/tpch_output/tpch_output_5/output_16.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_12.scala > ./tpch/tpch_output/tpch_output_5/output_12.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_13.scala > ./tpch/tpch_output/tpch_output_5/output_13.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_11.scala > ./tpch/tpch_output/tpch_output_5/output_11.txt
./bin/spark-shell --driver-memory 12g -i ./tpch/tpch_spark/spark_command_10.scala > ./tpch/tpch_output/tpch_output_5/output_10.txt
